image: python
  
build:
  stage: build
  tags:
    - docker
  before_script:
    - pip3 install -r requirements.txt
    - python --version
    - docker run --privileged -d docker:dind
  script:
      - cd main
      - python manage.py test cs14.tests
      - python manage.py test cs14.model_tests
      - python manage.py test cs14.language_extension_test


