image: python
  
build:
  stage: build
  tags:
    - docker
  before_script:
    - apt-get update -y
    - apt-get install docker.io -y
    - service docker start
    - pip3 install -r requirements.txt
    - python --version
    
   
  script:
      - cd main
      - python manage.py test cs14.tests
      - python manage.py test cs14.reviewtests
     


