image: docker:19.03.12

variables:
  # When using dind service, we need to instruct docker to talk with
  # the daemon started inside of the service. The daemon is available
  # with a network connection instead of the default
  # /var/run/docker.sock socket. Docker 19.03 does this automatically
  # by setting the DOCKER_HOST in
  # https://github.com/docker-library/docker/blob/d45051476babc297257df490d22cbd806f1b11e4/19.03/docker-entrypoint.sh#L23-L29
  #
  # The 'docker' hostname is the alias of the service container as described at
  # https://docs.gitlab.com/ee/ci/docker/using_docker_images.html#accessing-the-services.
  #
  # Specify to Docker where to create the certificates, Docker will
  # create them automatically on boot, and will create
  # `/certs/client` that will be shared between the service and job
  # container, thanks to volume mount from config.toml
  DOCKER_TLS_CERTDIR: "/certs"

services:
  - docker:19.03.12-dind
build:
  stage: build
  tags:
    - docker
  before_script:
    
    - apk add --update --no-cache python3 
    - ln -sf python3 /usr/bin/python
    - python3 -m ensurepip
    - apk add build-base python3-dev py-pip jpeg-dev zlib-dev
    - env LIBRARY_PATH=/lib:/usr/lib
    - pip3 install --no-cache --upgrade pip setuptools
    - pip3 install -r requirements.txt
    - python --version
    - cd main 
    - cd static
    - cd python
    - docker build -t coding-image .
    - cd ..
    - cd ..
    - cd ..
    
   
  script:
      - cd main
      - python manage.py test cs14.model_tests
      - python manage.py test cs14.language_extension_test
      - python manage.py test cs14.reviewtests

