image: python



build:
  stage: build
  tags:
    - docker
  before_script:
    - docker run -ti -v /var/run/docker.sock:/var/run/docker.sock docker
    - pip3 install -r requirements.txt
    - python --version
    
   
  script:
      - cd main
      - python manage.py test cs14.tests
      - python manage.py test cs14.reviewtests
     


